production:
  adapter: postgresql
  database: d5blu6uea8653o 
  username: gyfrmaivhugsxs
  host: ec2-54-243-187-196.compute-1.amazonaws.com
  password: zBJ8puEsJA2moJUJgt23KFNPp

development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: rurukish_simulator_development
  pool: 5
  username: root
  password: password

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: rurukish_simulator_test
  pool: 5
  username: root
  password: password
