production:
  adapter: postgresql
  database: d5blu6uea8653o 
  username: gyfrmaivhugsxs
  host: ec2-54-243-187-196.compute-1.amazonaws.com
  password: zBJ8puEsJA2moJUJgt23KFNPp

test:
  host: localhost
  username: ubuntu
  database: circle_ruby_test
  adapter: postgresql

development:
  adapter: postgresql
  database: rurukish_development
  pool: 5
  username: rurukish
  password: rurukish
