production:
  adapter: postgresql
  database: dfg2pm2jft78e6
  username: rbhtspsnoabnuw
  host: ec2-204-236-226-63.compute-1.amazonaws.com

test:
  host: localhost
  username: ubuntu
  database: circle_ruby_test
  adapter: postgresql

development:
  adapter: postgresql
  database: rurukish_development
  pool: 5
  username: rurukish
  password: rurukish
