production:
  adapter: postgresql
  database: rurukish
  username: rurukish
  password: rurukish

test:
  host: localhost
  username: ubuntu
  database: circle_ruby_test
  adapter: postgresql

development:
  adapter: postgresql
  database: rurukish_development
  pool: 5
  username: rurukish
  password: rurukish
